# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '2f0c4e55-266c-4ef9-96dd-a4a62813f229'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRMPipeline-rg'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName ARMTraining -linkedTemplateUri https://raw.githubusercontent.com/niroland/ARM/main/CreateWebApp/linkedStorageAccount.json?token=AL5LYDWKVKWXGHYV4GV3BP27PTFQ4'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'